openapi: 3.0.1
info:
  title: Image Description Service
  description: This service describes an image based on its URL.
  version: 1.0.0
servers:
  - url: http://localhost:5003
paths:
  /predict:
    post:
      operationId: predict
      summary: Get description of the image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the image.
              required:
                - url
      responses:
        200:
          description: Description of the image
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string